<?php

namespace AppBundle\Repository;

/**
 * LSdirRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class LSdirRepository extends \Doctrine\ORM\EntityRepository
{
}
